"""SDK-independent domain types."""

from vehicle_intelligence.domain.audit import AuditActor, AuditLog
from vehicle_intelligence.domain.camera import Camera, CameraHealth, SecretUri
from vehicle_intelligence.domain.dataset_registry import (
    DatasetHubSyncJob,
    DatasetHubSyncStatus,
    DatasetRegistryCapabilities,
    DetectorDatasetExport,
    DetectorDatasetSampleAnnotation,
    DetectorDatasetSampleBox,
    DetectorDatasetSampleImage,
    DetectorDatasetSampleKind,
    DetectorDatasetSamplePage,
    DetectorDatasetSamplePreview,
    DetectorDatasetVersion,
)
from vehicle_intelligence.domain.detection import (
    Detection,
    ModelMetadata,
    OCRCharacter,
    OCRResult,
    PlateDetection,
    TrackedDetection,
)
from vehicle_intelligence.domain.discovery import OnvifDiscoveredDevice
from vehicle_intelligence.domain.enums import (
    ActionExecutionStatus,
    AlertSeverity,
    AlertStatus,
    AuditAction,
    AuditResourceType,
    AuthenticationMethod,
    CameraDirection,
    CameraStatus,
    DatasetSampleReason,
    DatasetSampleStatus,
    DatasetSampleType,
    Direction,
    EventStatus,
    EventType,
    IdentityReviewAction,
    ReIDVerdict,
    RuleActionType,
    RuleConditionOperator,
    TrackStatus,
    UserRole,
    VehicleIdentityStatus,
    WatchlistType,
)
from vehicle_intelligence.domain.events import (
    AITrace,
    CameraSnapshot,
    MediaReferences,
    PlateEvidence,
    PlateReview,
    VehicleEvent,
    VehicleEvidence,
)
from vehicle_intelligence.domain.frame import VideoFrame
from vehicle_intelligence.domain.geometry import BoundingBox, Point
from vehicle_intelligence.domain.identity import (
    EmbeddingModel,
    EmbeddingReference,
    EmbeddingVector,
    PlateIdentitySignal,
    VectorNeighbor,
    VehicleFingerprint,
    VehicleIdentity,
)
from vehicle_intelligence.domain.journey import (
    JourneyObservation,
    JourneySegment,
    VehicleJourney,
)
from vehicle_intelligence.domain.live import (
    LiveFrameMetadata,
    LiveFramePacket,
    LivePlateOverlay,
    LiveVehicleOverlay,
)
from vehicle_intelligence.domain.plate import (
    CharacterCorrection,
    PlateCandidate,
    PlateNormalization,
    PlateObservation,
    PlateQuality,
)
from vehicle_intelligence.domain.policy import (
    ActionExecution,
    Alert,
    AlertSource,
    Rule,
    RuleAction,
    RuleCondition,
    RuleSnapshot,
    WatchlistEntry,
)
from vehicle_intelligence.domain.quality import (
    DailyQualityPoint,
    DatasetFeedbackMetrics,
    ModelQualityReport,
    ModelQualitySlice,
    QualityMetrics,
)
from vehicle_intelligence.domain.reid import (
    IdentityMergeReview,
    IdentityReviewer,
    IdentityReviewResult,
    IdentitySplitReview,
    ReIDScore,
    ReIDSignals,
)
from vehicle_intelligence.domain.retention import (
    LifecycleReconcileResult,
    MediaKind,
    MediaRetentionClaim,
)
from vehicle_intelligence.domain.review import DatasetSample, OCRDatasetPrediction
from vehicle_intelligence.domain.security import Principal
from vehicle_intelligence.domain.topology import CameraTopologyEdge, CrossCameraCandidate
from vehicle_intelligence.domain.tracking import ImageCandidate, TrajectoryPoint, VehicleTrack

__all__ = [
    "AITrace",
    "ActionExecution",
    "ActionExecutionStatus",
    "Alert",
    "AlertSeverity",
    "AlertSource",
    "AlertStatus",
    "AuditAction",
    "AuditActor",
    "AuditLog",
    "AuditResourceType",
    "AuthenticationMethod",
    "BoundingBox",
    "Camera",
    "CameraDirection",
    "CameraHealth",
    "CameraSnapshot",
    "CameraStatus",
    "CameraTopologyEdge",
    "CharacterCorrection",
    "CrossCameraCandidate",
    "DatasetSample",
    "DatasetSampleReason",
    "DatasetSampleStatus",
    "DatasetSampleType",
    "DailyQualityPoint",
    "DatasetFeedbackMetrics",
    "DatasetHubSyncJob",
    "DatasetHubSyncStatus",
    "DatasetRegistryCapabilities",
    "DetectorDatasetSampleAnnotation",
    "DetectorDatasetSampleBox",
    "DetectorDatasetSampleImage",
    "DetectorDatasetSampleKind",
    "DetectorDatasetSamplePage",
    "DetectorDatasetSamplePreview",
    "Detection",
    "DetectorDatasetExport",
    "DetectorDatasetVersion",
    "Direction",
    "EventStatus",
    "EventType",
    "IdentityMergeReview",
    "IdentityReviewer",
    "IdentityReviewAction",
    "IdentityReviewResult",
    "IdentitySplitReview",
    "JourneyObservation",
    "JourneySegment",
    "EmbeddingModel",
    "EmbeddingReference",
    "EmbeddingVector",
    "ImageCandidate",
    "LiveFrameMetadata",
    "LiveFramePacket",
    "LivePlateOverlay",
    "LiveVehicleOverlay",
    "LifecycleReconcileResult",
    "MediaKind",
    "MediaReferences",
    "MediaRetentionClaim",
    "ModelMetadata",
    "ModelQualityReport",
    "ModelQualitySlice",
    "OCRCharacter",
    "OCRResult",
    "OnvifDiscoveredDevice",
    "PlateCandidate",
    "PlateDetection",
    "PlateEvidence",
    "PlateIdentitySignal",
    "PlateReview",
    "PlateNormalization",
    "PlateObservation",
    "PlateQuality",
    "Point",
    "OCRDatasetPrediction",
    "Principal",
    "QualityMetrics",
    "Rule",
    "RuleAction",
    "RuleActionType",
    "RuleCondition",
    "RuleConditionOperator",
    "RuleSnapshot",
    "ReIDScore",
    "ReIDSignals",
    "ReIDVerdict",
    "SecretUri",
    "TrackedDetection",
    "TrackStatus",
    "TrajectoryPoint",
    "UserRole",
    "VectorNeighbor",
    "VehicleEvent",
    "VehicleEvidence",
    "VehicleFingerprint",
    "VehicleIdentity",
    "VehicleIdentityStatus",
    "VehicleJourney",
    "VehicleTrack",
    "VideoFrame",
    "WatchlistEntry",
    "WatchlistType",
]
