from enum import StrEnum


class Direction(StrEnum):
    ENTER = "ENTER"
    EXIT = "EXIT"
    UNKNOWN = "UNKNOWN"


class EventType(StrEnum):
    VEHICLE_ENTER = "VEHICLE_ENTER"
    VEHICLE_EXIT = "VEHICLE_EXIT"
    VEHICLE_DETECTED = "VEHICLE_DETECTED"


class EventStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    NO_PLATE = "NO_PLATE"
    UNREADABLE = "UNREADABLE"


class DatasetSampleType(StrEnum):
    PLATE_OCR = "PLATE_OCR"


class DatasetSampleReason(StrEnum):
    HUMAN_CORRECTION = "HUMAN_CORRECTION"
    HUMAN_CONFIRMATION = "HUMAN_CONFIRMATION"


class DatasetSampleStatus(StrEnum):
    READY = "READY"
    EXPORTING = "EXPORTING"
    EXPORTED = "EXPORTED"
    EXPORT_FAILED = "EXPORT_FAILED"


class TrackStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FINALIZED = "FINALIZED"


class VehicleIdentityStatus(StrEnum):
    ACTIVE = "ACTIVE"
    MERGED = "MERGED"
    SPLIT = "SPLIT"
    ARCHIVED = "ARCHIVED"


class ReIDVerdict(StrEnum):
    MATCH = "MATCH"
    REVIEW = "REVIEW"
    REJECT = "REJECT"


class IdentityReviewAction(StrEnum):
    MERGE = "MERGE"
    SPLIT = "SPLIT"


class CameraStatus(StrEnum):
    CONNECTING = "CONNECTING"
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    STOPPED = "STOPPED"


class CameraDirection(StrEnum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    BOTH = "BOTH"


class WatchlistType(StrEnum):
    WHITELIST = "WHITELIST"
    BLACKLIST = "BLACKLIST"
    VIP = "VIP"
    STAFF = "STAFF"
    CONTRACTOR = "CONTRACTOR"
    DELIVERY = "DELIVERY"


class RuleConditionOperator(StrEnum):
    EQ = "EQ"
    NEQ = "NEQ"
    IN = "IN"
    NOT_IN = "NOT_IN"
    CONTAINS = "CONTAINS"
    EXISTS = "EXISTS"


class RuleActionType(StrEnum):
    OPEN_BARRIER = "OPEN_BARRIER"
    CREATE_ALERT = "CREATE_ALERT"
    WEBHOOK = "WEBHOOK"
    HTTP_REQUEST = "HTTP_REQUEST"
    NOTIFICATION = "NOTIFICATION"
    LOG = "LOG"


class ActionExecutionStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class AlertStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class AlertSeverity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class AuthenticationMethod(StrEnum):
    API_KEY = "API_KEY"
    OIDC = "OIDC"
    SYSTEM = "SYSTEM"
    DEVELOPMENT = "DEVELOPMENT"


class AuditAction(StrEnum):
    CAMERA_CREATED = "CAMERA_CREATED"
    CAMERA_UPDATED = "CAMERA_UPDATED"
    CAMERA_DELETED = "CAMERA_DELETED"
    CAMERA_ENABLED = "CAMERA_ENABLED"
    CAMERA_DISABLED = "CAMERA_DISABLED"
    CAMERA_CONNECTION_TESTED = "CAMERA_CONNECTION_TESTED"
    CAMERA_DISCOVERY_RUN = "CAMERA_DISCOVERY_RUN"
    WATCHLIST_CREATED = "WATCHLIST_CREATED"
    WATCHLIST_UPDATED = "WATCHLIST_UPDATED"
    WATCHLIST_DELETED = "WATCHLIST_DELETED"
    RULE_CREATED = "RULE_CREATED"
    RULE_UPDATED = "RULE_UPDATED"
    RULE_DELETED = "RULE_DELETED"
    ALERT_ACKNOWLEDGED = "ALERT_ACKNOWLEDGED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    PLATE_CORRECTED = "PLATE_CORRECTED"
    PLATE_CONFIRMED = "PLATE_CONFIRMED"
    CAMERA_CREDENTIALS_ROTATED = "CAMERA_CREDENTIALS_ROTATED"
    CAMERA_TOPOLOGY_CREATED = "CAMERA_TOPOLOGY_CREATED"
    CAMERA_TOPOLOGY_UPDATED = "CAMERA_TOPOLOGY_UPDATED"
    CAMERA_TOPOLOGY_DELETED = "CAMERA_TOPOLOGY_DELETED"
    VEHICLE_IDENTITIES_MERGED = "VEHICLE_IDENTITIES_MERGED"
    VEHICLE_IDENTITY_SPLIT = "VEHICLE_IDENTITY_SPLIT"
    DETECTOR_SAMPLE_REVIEWED = "DETECTOR_SAMPLE_REVIEWED"
    DETECTOR_DATASET_PROMOTION_STARTED = "DETECTOR_DATASET_PROMOTION_STARTED"
    DETECTOR_DATASET_HF_SYNC_STARTED = "DETECTOR_DATASET_HF_SYNC_STARTED"


class AuditResourceType(StrEnum):
    CAMERA = "CAMERA"
    WATCHLIST_ENTRY = "WATCHLIST_ENTRY"
    RULE = "RULE"
    ALERT = "ALERT"
    VEHICLE_EVENT = "VEHICLE_EVENT"
    CAMERA_TOPOLOGY = "CAMERA_TOPOLOGY"
    VEHICLE_IDENTITY = "VEHICLE_IDENTITY"
    DETECTOR_DATASET_SAMPLE = "DETECTOR_DATASET_SAMPLE"
    DETECTOR_DATASET = "DETECTOR_DATASET"
